import assert from "node:assert/strict";
import test from "node:test";
import { readFileSync } from "node:fs";

const server = readFileSync(new URL("../server.js", import.meta.url), "utf8");
const chat = readFileSync(new URL("../public/chat-app-20260821-1310.js", import.meta.url), "utf8");
const html = readFileSync(new URL("../public/chat.html", import.meta.url), "utf8");
const helperStart = server.indexOf("const FUNCTION_MODEL_ROLES");
const helperEnd = server.indexOf("async function callFunctionModel", helperStart);
const thresholdStart = server.indexOf("function configuredSummaryThreshold");
const thresholdEnd = server.indexOf("async function updateRollingDaySummary", thresholdStart);
assert.notEqual(helperStart, -1);
assert.notEqual(helperEnd, -1);
assert.notEqual(thresholdStart, -1);
const helpers = new Function("getFunctionalChatPreset", `${server.slice(helperStart, helperEnd)};return { functionalModelError, functionalModelStatus };`)((settings, value) => ({ model: value?.split("::")[1] || "", provider: "openai" }));
const threshold = new Function(`${server.slice(thresholdStart, thresholdEnd)};return configuredSummaryThreshold;`)();

test("1. main-model calls are status-tracked", () => assert.match(server, /callFunctionModel\("main", preset/));
test("2. unused summary model reports unused", () => assert.equal(helpers.functionalModelStatus({ functions:{} }, "summary").status, "unused"));
test("3. summary success is tracked separately", () => assert.match(server, /callFunctionModel\("summary", preset/));
test("4. 401 is simplified", () => assert.deepEqual(helpers.functionalModelError(new Error("模型请求失败 401")), { code:"401", message:"API key 无效" }));
test("5. 402 and balance errors are simplified", () => assert.equal(helpers.functionalModelError(new Error("余额不足")).message, "余额不足"));
test("6. 429 is simplified", () => assert.deepEqual(helpers.functionalModelError(new Error("请求失败 429")), { code:"429", message:"quota exceeded" }));
test("7. image failures are status-tracked", () => assert.match(server, /callFunctionModel\("image", preset/));
test("8. opening model settings marks status viewed", () => assert.match(chat, /function-model-status\/viewed/));
test("9. viewing does not erase the error record", () => assert.match(server, /settings\.lastModelStatusViewedAt = chatNow\(\)/));
test("10. a newer failure becomes unread", () => assert.match(server, /lastErrorAt > String\(settings\.lastModelStatusViewedAt/));
test("11. a newer success restores normal state", () => assert.match(server, /lastErrorAt && lastErrorAt > lastSuccessAt \? "error" : \(lastSuccessAt \? "normal" : "unused"\)/));
test("12. new default summary threshold is 48", () => assert.match(server, /summaryThreshold:48/));
test("13. saved legacy value 24 remains valid", () => assert.equal(threshold(24), 24));
test("14. user can set 24", () => assert.equal(threshold(24), 24));
test("15. user can set 60", () => assert.equal(threshold(60), 60));
test("16. user can set 120", () => assert.equal(threshold(120), 120));
test("17. out-of-range values are limited", () => { assert.equal(threshold(1), 24); assert.equal(threshold(999), 120); });
test("18. summary no longer clamps at 24", () => assert.doesNotMatch(server.slice(thresholdStart, server.indexOf("function appendCurrentDaySummary", thresholdStart)), /Math\.min\(24, configuredThreshold\)/));
test("19. automatic summary compares pending message count with configured threshold", () => assert.match(server, /pending\.length < threshold/));
test("20. summary failures preserve raw messages", () => assert.match(server, /raw chat messages stay intact/));
test("21. immediate summary invokes the shared rolling-summary path", () => assert.match(server, /updateRollingDaySummary\(\{ conversation, history, settings, day, force:true \}\)/));
test("22. immediate-summary failure records summary status", () => assert.match(server, /callFunctionModel\("summary", preset/));
test("23. immediate-summary failure does not delete context", () => assert.doesNotMatch(server.slice(server.indexOf('app.post("/api/chat/conversations/:id/summary"'), server.indexOf("// ---- 清空聊天")), /discardChatMessages|writeChatMessages/));
test("24. summary never retries with the main model after a failure", () => assert.doesNotMatch(server.slice(server.indexOf("async function updateRollingDaySummary"), server.indexOf("function appendCurrentDaySummary")), /catch[\s\S]*?config\.main/));
test("25. model-status card uses theme variables", () => assert.match(chat, /function-model-status-v94[\s\S]*?var\(--chat-text\)/));
test("26. dark mode uses the project selector", () => assert.match(chat, /html\[data-appearance="dark"\] \.function-model-status-v94/));
test("27. status API response exposes no credential fields", () => { const block = server.slice(server.indexOf('app.get("/api/chat/function-model-status"'), server.indexOf("// ---- Claude Code usage")); assert.doesNotMatch(block, /apiKey|bearerToken|authorization|headers/i); });
